use_frameworks!

platform :ios, '10.0'

target 'KalturaClient_Example' do
  pod 'KalturaClient', :path => '../'

  target 'KalturaClient_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 5.0.1'
    pod 'Nimble', '~> 10.0.0'
  end
end
