use_frameworks!

target 'KalturaClient_Example' do
  pod 'KalturaClient', :path => '../'

  target 'KalturaClient_Tests' do
    inherit! :search_paths

    pod 'KalturaClient', :path => '../'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
