name: Clients Generation
on:
  push:
    branches:
      - cicd
  workflow_dispatch:

env:
  client_name: all

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        id: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.2"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Clients
        run: |
          ./gen-ovp.sh
          tar czf dist.tar.gz dist

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.tar.gz

  build:
    runs-on: ubuntu-latest
    needs: [generate]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
    - run: |
        ls -l 
        tar xzf dist.tar.gz
        ls -lR dist
